version: "3"
services:
  spark:
    image: apache/spark:latest
    environment:
      - SPARK_MASTER=local[2]
      - SPARK_DRIVER_MEMORY=2g


  jupyter:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - SPARK_MASTER=spark://spark:7077
